### PR TITLE
Add a randomforest option to create many dependent jobs.

### PR DESCRIPTION
**Pull request by mrdmnd**
Also adds an **init**.py file to lib/texttable so it loads properly.

Here's some (printed) sample output:

Tue Jan 21 14:37:25 mrdmnd@anglerfish ~/airbnb/chronos-utils  (random-forests) $ ./chronos.py jobs --createforest 15
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB0', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB1', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB2', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB0']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB3', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB4', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB3', 'DEPENDENTJOB2']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB5', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB3']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB6', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB7', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB5']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB8', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB3', 'DEPENDENTJOB1']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB9', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB6']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB10', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB0']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB11', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB12', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': []}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB13', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB8']}
{'disabled': False, 'async': False, 'command': 'sleep 50', 'name': 'DEPENDENTJOB14', 'executor': '', 'owner': 'rob@fake.com', 'epsilon': 'PT15M', 'parents': ['DEPENDENTJOB4', 'DEPENDENTJOB8']}
Created 15 dependent job(s) on local Chronos

### CODE REVIEW

**Comment by ssorallen** [comment]
This is great, thanks for the changes.

I tried using `--createforest 5` on a Chronos instance with no previous jobs, and I got errors that the parents didn't exist:

```
INFO: Received request for job:DependencyBasedJob(Set(),DEPENDENTJOB0,sleep 50,PT15M,0,0,,,2,rob@fake.com,,,false,0.0,0,0,false,0,ListBuffer())
Jan 21, 2014 4:39:53 PM com.airbnb.scheduler.api.DependentJobResource post
WARNING: Exception while serving request
java.lang.Exception: Error, parent does not exist
    at com.airbnb.scheduler.api.DependentJobResource.post(DependentJobResource.scala:37)
```

It looks like it creates _only_ dependent jobs, which means there's never a root of the dependency tree. Is it possible to make this start from an empty tree?

**Comment by mrdmnd** [comment]
Derp - that's a great point. I didn't actually test this with a Chronos
instance >.<

I forgot that if you create a dependent job, it has to actually have a
non-empty parents list to be valid.

I'll fix this by setting the ones with empty parents lists to just be
scheduled jobs instead.

Nice find! =)

**Comment by ssorallen** [comment]
This is looking good. I still think it's possible to generate dependent jobs with no available parents though. If you specify `--createforest 5` with an empty task tree, `i` will be greater than 2, and the random number could decide to make the first job a dependent one.

I think the conditions need to check the number of available parents as well before making a job dependent.

**Comment by mrdmnd** [comment]
Yeah, also seems correct. Fix pushed.

**Comment by ssorallen** [comment]
With the couple patches this works great. Thanks for adding it. I will update the README to include a description of this.

**Comment by ssorallen** [comment]
Something I missed was the jobs are all named with `"DEPENDENTJOB%i" % i` where `i` is the value of the iterator. If you run the command multiple times, it uses the same names over and over. In `--create` I append `datetime.datetime.utcnow()`, which has resolution to 1/100,000th of a second and is granular enough to produce unique values between iterations in the loop.

I will update `--createforest` to produce unique job names.

**Comment by mrdmnd** [comment]
Seems smart, good catch =)

**Comment by ssorallen** [comment]
Fixed in 7d8214e2c4a6188fb8e37a4e274b6989112264f3.

**Pull request merged**
